spring:
  redis:
    database: 0
    host: 39.100.86.77
    port: 16379
    timeout: 10000ms
    jedis:
      pool:
        max-active: 16
        max-idle: 4

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
